import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function Header() {
  return (
    <header>
      
      <div>
        <nav>
          <div>
            <Link href="/">Swotooth Mountain</Link>
          </div>
          <div>
          <Link href="/mountain"> Mountain</Link>
          </div>
        </nav>
        
      </div>
    </header>
  )
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       <Header></Header>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
